export const tableData = [
  {
    company: "Adobe design suite",
    login: "thepeopleteam@think201.com",
    password: "45_6tg5d%3f01d",
    token: "Adobedesign",
    link: "https://www.w3schools.com/js/js_loop_for.asp",
    tags: ["admin", "git"],
    color: "red",
  },
  {
    company: "Milan",
    login: "Dummy@123",
    password: "45_6tg5d%3f01d",
    token: "Milan",
    link: "https://mui.com/material-ui/react-text-field/.asp",
    tags: ["admin", "git"],
    color: "purple",
  },
  {
    company: "Google",
    login: "Dummy@google",
    password: "fdfdfdf",
    token: "Null",
    link: "dummyjson.com",
    tags: ["admin", "git"],
    color: "green",
  },
  {
    company: "Figma",
    login: "thepeopleteam@think201.com",
    password: "45_6tg5d%3f01d",
    token: "token",
    link: "https://www.figma.com",
    tags: ["admin", "git"],
    color: "#edd869",
  },
  {
    company: "Storyblocks",
    login: "thepeopleteam@think201.com",
    password: "password",
    token: "something",
    link: "https://www.figma.com",
    tags: ["admin", "git"],
    color: "",
  },
];
